# Generated by Django 2.2.1 on 2019-08-02 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2019, 8, 2, 12, 22, 3, 390440, tzinfo=utc))),
                ('slug', models.SlugField(allow_unicode=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
