# Generated by Django 2.2.1 on 2019-08-02 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190802_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 12, 59, 2, 577178, tzinfo=utc)),
        ),
    ]
