# Generated by Django 2.2.1 on 2019-08-06 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190806_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 11, 12, 45, 55249, tzinfo=utc)),
        ),
    ]
