# Generated by Django 2.2.1 on 2019-08-06 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190806_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 13, 25, 52, 238800, tzinfo=utc)),
        ),
    ]
