# Generated by Django 2.2.1 on 2019-08-07 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190807_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 6, 43, 39, 644075, tzinfo=utc)),
        ),
    ]
