# Generated by Django 2.2.1 on 2019-08-08 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190808_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 12, 56, 20, 120825, tzinfo=utc)),
        ),
    ]
