# Generated by Django 2.2.1 on 2019-08-10 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190810_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 10, 30, 51, 358985, tzinfo=utc)),
        ),
    ]
