# Generated by Django 2.2.1 on 2019-08-14 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190814_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 9, 19, 56, 299834, tzinfo=utc)),
        ),
    ]
