# Generated by Django 2.2.1 on 2019-08-17 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20190817_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_genre.jpg', upload_to='genre_pics')),
                ('info', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 7, 53, 13, 541807, tzinfo=utc)),
        ),
    ]
