# Generated by Django 2.2.1 on 2019-08-17 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20190817_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts & Entertainment'), ('Industry', 'Industry'), ('Innovation', 'Innovation & Tech'), ('Life', 'Life'), ('Society', 'Society'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 8, 6, 37, 343124, tzinfo=utc)),
        ),
    ]
