# Generated by Django 2.2.1 on 2019-08-17 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190817_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 11, 11, 51, 953570, tzinfo=utc)),
        ),
    ]
