# Generated by Django 2.2.1 on 2019-08-17 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20190817_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 11, 12, 37, 411228, tzinfo=utc)),
        ),
    ]
