# Generated by Django 2.2.1 on 2019-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_by', to='users.Profile'),
        ),
    ]
