# Generated by Django 2.2.1 on 2019-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_profile_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='_profile_follows_+', to='users.Profile'),
        ),
    ]
