# Generated by Django 2.2.1 on 2019-08-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20190820_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='claps',
            field=models.IntegerField(default=0),
        ),
    ]
