# Generated by Django 2.2.1 on 2019-08-26 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0052_auto_20190821_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Story')),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='respones_claps',
            field=models.ManyToManyField(blank=True, related_name='clapped_by', to='users.Responses'),
        ),
    ]
