# Generated by Django 2.2.1 on 2019-08-26 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20190826_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
