# Generated by Django 2.2.1 on 2019-08-26 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_responses_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='respones_claps',
        ),
        migrations.AddField(
            model_name='profile',
            name='response_claps',
            field=models.ManyToManyField(blank=True, related_name='resonse_by', to='users.Responses'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
