# Generated by Django 2.2.1 on 2019-08-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20190826_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
