# Generated by Django 2.2.1 on 2019-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20190827_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts & Entertainment'), ('Industry', 'Industry'), ('Innovation', 'Innovation & Tech'), ('Life', 'Life'), ('Society', 'Society'), ('Miscellaneous', 'Miscellaneous')], max_length=100),
        ),
    ]
