# Generated by Django 2.2.1 on 2019-08-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20190828_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
