# Generated by Django 2.2.1 on 2019-08-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_remove_genre_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
       
    ]
