# Generated by Django 2.2.1 on 2019-08-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20190828_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='category',
            new_name='category1',
        ),
    ]
