# Generated by Django 2.2.1 on 2019-08-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20190828_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreCategory',
            new_name='GenreCategory1',
        ),
    ]
