# Generated by Django 2.2.1 on 2019-08-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20190828_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='category1',
        ),
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.CharField(choices=[('Arts & Entertainment', 'Arts & Entertainment'), ('Industry', 'Industry'), ('Innovation & Tech', 'Innovation & Tech'), ('Life', 'Life'), ('Society', 'Society'), ('Miscellaneous', 'Miscellaneous')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='GenreCategory1',
        ),
    ]
