# Generated by Django 2.2.1 on 2019-08-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20190828_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='category',
        ),
    ]
