# Generated by Django 2.2.1 on 2019-08-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_remove_story_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Responses')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Story')),
            ],
        ),
    ]
