# Generated by Django 2.2.1 on 2019-08-31 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
