# Generated by Django 2.2.1 on 2019-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageData1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story1', models.CharField(choices=[('Yes, Post-Vacation Burnout Is a Thing ok', 'yes-post-vacation-burnout-is-a-thing-20'), ('The AirPod Connect Sound Is Beautiful', 'the-airpod-connect-sound-is-beautiful-23')], max_length=1000)),
                ('story2', models.CharField(choices=[('Yes, Post-Vacation Burnout Is a Thing ok', 'yes-post-vacation-burnout-is-a-thing-20'), ('The AirPod Connect Sound Is Beautiful', 'the-airpod-connect-sound-is-beautiful-23')], max_length=1000)),
                ('story3', models.CharField(choices=[('Yes, Post-Vacation Burnout Is a Thing ok', 'yes-post-vacation-burnout-is-a-thing-20'), ('The AirPod Connect Sound Is Beautiful', 'the-airpod-connect-sound-is-beautiful-23')], max_length=1000)),
                ('story4', models.CharField(choices=[('Yes, Post-Vacation Burnout Is a Thing ok', 'yes-post-vacation-burnout-is-a-thing-20'), ('The AirPod Connect Sound Is Beautiful', 'the-airpod-connect-sound-is-beautiful-23')], max_length=1000)),
                ('story5', models.CharField(choices=[('Yes, Post-Vacation Burnout Is a Thing ok', 'yes-post-vacation-burnout-is-a-thing-20'), ('The AirPod Connect Sound Is Beautiful', 'the-airpod-connect-sound-is-beautiful-23')], max_length=1000)),
            ],
        ),
    ]
