# Generated by Django 2.2.1 on 2019-08-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20190826_1515'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagedata1',
            name='story1',
        ),
        migrations.AddField(
            model_name='homepagedata1',
            name='story1',
            field=models.ManyToManyField(blank=True, related_name='st1', to='users.Story'),
        ),
        migrations.RemoveField(
            model_name='homepagedata1',
            name='story2',
        ),
        migrations.AddField(
            model_name='homepagedata1',
            name='story2',
            field=models.ManyToManyField(blank=True, related_name='st2', to='users.Story'),
        ),
        migrations.RemoveField(
            model_name='homepagedata1',
            name='story3',
        ),
        migrations.AddField(
            model_name='homepagedata1',
            name='story3',
            field=models.ManyToManyField(blank=True, related_name='st3', to='users.Story'),
        ),
        migrations.RemoveField(
            model_name='homepagedata1',
            name='story4',
        ),
        migrations.AddField(
            model_name='homepagedata1',
            name='story4',
            field=models.ManyToManyField(blank=True, related_name='st4', to='users.Story'),
        ),
        migrations.RemoveField(
            model_name='homepagedata1',
            name='story5',
        ),
        migrations.AddField(
            model_name='homepagedata1',
            name='story5',
            field=models.ManyToManyField(blank=True, related_name='st5', to='users.Story'),
        ),
    ]
