# Generated by Django 2.2.1 on 2019-08-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20190826_1515'),
        ('blog', '0002_auto_20190827_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagedata1',
            old_name='story2',
            new_name='featured_story',
        ),
        migrations.RenameField(
            model_name='homepagedata1',
            old_name='story1',
            new_name='homepage_story',
        ),
        migrations.RemoveField(
            model_name='homepagedata1',
            name='story3',
        ),
        migrations.RemoveField(
            model_name='homepagedata1',
            name='story4',
        ),
        migrations.RemoveField(
            model_name='homepagedata1',
            name='story5',
        ),
        migrations.AddField(
            model_name='homepagedata1',
            name='popular_story',
            field=models.ManyToManyField(blank=True, related_name='st3', to='users.Story'),
        ),
    ]
