# Generated by Django 2.2.1 on 2019-08-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20190827_1520'),
        ('blog', '0003_auto_20190827_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomepageData1',
            new_name='HomepageData',
        ),
    ]
